In [1]:
from tianshou.data import ReplayBuffer

In [2]:
buf = ReplayBuffer(size=9, stack_num=4, ignore_obs_next=True)
for i in range(16):
    done = i % 5 == 0
    buf.add(obs={'id':i}, act=i, rew=i, done=done, obs_next={'id':i+1})
print(buf)

ReplayBuffer(
    obs: Batch(
             id: array([ 9, 10, 11, 12, 13, 14, 15,  7,  8]),
         ),
    act: array([ 9, 10, 11, 12, 13, 14, 15,  7,  8]),
    rew: array([ 9, 10, 11, 12, 13, 14, 15,  7,  8]),
    done: array([False,  True, False, False, False, False,  True, False, False]),
    info: Batch(),
    policy: Batch(),
)


In [3]:
import numpy as np

In [9]:
index = np.arange(len(buf))
index.ndim

1

In [8]:
print(buf.get([1,2], 'obs').id)

[[ 7  8  9 10]
 [11 11 11 11]]


In [10]:
from tianshou.data import Batch

In [25]:
data = Batch(a=np.array([[0.0, 2.0], [1.0, 3.0], [3.0, 3.0]]), b=[[5, -5], [1, -2]])

In [26]:
print(len(data))

2


In [39]:
print(data)

Batch(
    a: array([[0., 3.],
              [1., 4.],
              [3., 4.]]),
    b: array([[ 5, -4],
              [ 1, -1]]),
)


In [27]:
print(data.shape)

[2, 2]


In [37]:
for sample in data:
    print(sample)

Batch(
    a: array([0., 2.]),
    b: array([ 5, -5]),
)
Batch(
    a: array([1., 3.]),
    b: array([ 1, -2]),
)


In [48]:
data[:,1] += 1
print(data)

Batch(
    a: array([[ 0., 10.],
              [ 1.,  5.],
              [ 3.,  5.]]),
    b: array([[5, 3],
              [1, 0]]),
)


In [49]:
data.a

array([[ 0., 10.],
       [ 1.,  5.],
       [ 3.,  5.]])

In [50]:
data = Batch(a=[5., 4.], b=np.zeros((2,3,4)))

In [52]:
data[0]

Batch(
    a: 5.0,
    b: array([[0., 0., 0., 0.],
              [0., 0., 0., 0.],
              [0., 0., 0., 0.]]),
)

In [68]:
b = Batch({'state': [None, None], 'c':[2., 'st'], 'd':[1., 0.]})    

'2.0'

In [56]:
data = Batch(a=[False, True], b=b)

In [58]:
data, data[0], data[1]

(Batch(
     a: array([False,  True]),
     b: Batch(
            c: array(['2.0', 'st'], dtype=object),
            d: array([1., 0.]),
        ),
 ),
 Batch(
     a: False,
     b: Batch(
            c: '2.0',
            d: 1.0,
        ),
 ),
 Batch(
     a: True,
     b: Batch(
            c: 'st',
            d: 0.0,
        ),
 ))

In [59]:
data[0] = Batch.empty(data[1])

/home/leeqh/anaconda3/envs/ts/lib/python3.8/site-packages/tianshou-0.2.6-py3.8.egg/tianshou/data/batch.py:620: UserWarning: You are calling Batch.empty on a NumPy scalar, which may cause undefined behaviors.
  warnings.warn('You are calling Batch.empty on a NumPy scalar, '


In [60]:
data

Batch(
    a: array([False,  True]),
    b: Batch(
           c: array([None, 'st'], dtype=object),
           d: array([0., 0.]),
       ),
)